import Head from 'next/head'
import { Categories,  PostCard, PostWidget } from '../components'
import { getPosts } from '../services'


export default function Home({ posts }) {
  console.log(posts)
  return (
    <div className="container mx-auto px-10 mb-8 text-white">
      <Head>
        <title>Gain Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 mt-10">
        <div className="lg:col-span-8 col-span-1 ">
          <div className="grid grid-cols-1 gap-6 md:grid-cols-2 ">

         
          {
              posts.map((post,index) =>  <PostCard post={post.node} key={post.node.title} />
              
              )
            }
            </div>
        </div>
        <div className='lg:col-span-4 col-span-1 k'>
          <div className="lg:sticky relative top-8 ">
            <PostWidget />
            <Categories />
          </div>

        </div>
      </div>
     
     
    </div>
  )
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: {
      posts
    }
  }
}
